### ISSUE TITLE
sorting order buycraft page

### ISSUE THREAD

**Issue by thunderlight411** [plan-player-analytics/Extension-Tebex#1]
The Buycraft module sorts the transactions based on username.
can this being switched to sort on date?

https://i.imgur.com/1RDtR1Y.png

When clicking on date its showing some kind of sorting but its still not showing a corrent order 
https://i.imgur.com/gmIEOAh.png

**Comment by Rsl1122** [comment]
Sort of related to https://github.com/plan-player-analytics/Plan/issues/1305

Seems like I forgot to close this issue tracker. Please see the linked issue for reasoning why date order is not currently used.
